// mock/ant-app/src/component/entity-rules/ScorePanel.tsx
import { Card, List, Progress, Tag, Typography } from 'antd';
import type { ScoreResult } from '../../types/entity-rules';

export const ScorePanel = ({ result }: { result?: ScoreResult }) => {
    if (!result) return null;

    return (
        <Card title={`评分结果 ${result.score}/${result.maxScore}`}>
            <Progress percent={Math.round((result.score / result.maxScore) * 100)} />
            <List
                dataSource={result.items}
                renderItem={(item) => (
                    <List.Item>
                        <Typography.Text>{item.key}</Typography.Text>
                        <Tag color={item.ok ? 'green' : 'red'}>{item.ok ? `+${item.score}` : '0'}</Tag>
                    </List.Item>
                )}
            />
        </Card>
    );
};

// mock/element-app/src/component/entity-rules/ScorePanel.vue
<template>
  <el-card v-if="result" :header="`评分结果 ${result.score}/${result.maxScore}`">
    <el-progress :percentage="Math.round((result.score / result.maxScore) * 100)" />
    <el-table :data="result.items" size="small" style="margin-top: 12px">
      <el-table-column prop="key" label="Key" />
      <el-table-column prop="score" label="Score" />
      <el-table-column label="OK">
        <template #default="scope">
          <el-tag :type="scope.row.ok ? 'success' : 'danger'">{{ scope.row.ok ? 'YES' : 'NO' }}</el-tag>
        </template>
      </el-table-column>
    </el-table>
  </el-card>
</template>

<script setup lang="ts">
import type { ScoreResult } from '../../types/entity-rules';

defineProps<{ result?: ScoreResult }>();
</script>
