// mock/ant-app/src/component/entity-rules/TaskBanner.tsx
import { Alert, Space, Typography } from 'antd';

export const TaskBanner = ({ title, description }: { title: string; description: string }) => (
    <Space direction="vertical" size={12} style={{ width: '100%' }}>
        <Typography.Title level={3} style={{ margin: 0 }}>
            {title}
        </Typography.Title>
        <Alert type="info" showIcon message={description} />
    </Space>
);

// mock/element-app/src/component/entity-rules/TaskBanner.vue
<template>
  <el-space direction="vertical" alignment="start" style="width: 100%">
    <h2 style="margin: 0">{{ title }}</h2>
    <el-alert :title="description" type="info" show-icon :closable="false" />
  </el-space>
</template>

<script setup lang="ts">
defineProps<{ title: string; description: string }>();
</script>
