// mock/ant-app/src/view/entity-rules/EntityRulesHome.tsx
import { Card, List, Space, Typography } from 'antd';
import { Link } from 'react-router-dom';
import { getOrderFormCaseOptions, getOrderListCaseOptions } from '../../service/entity-rules/case-service';

export const EntityRulesHome = () => {
    const fixtureLinks = [
        { to: '/entity-rules/fixtures/order-list', label: 'Fixture Order List' },
        { to: '/entity-rules/fixtures/order-form', label: 'Fixture Order Form' },
    ];
    const benchLinks = [
        ...getOrderListCaseOptions().map((item) => ({ to: `/entity-rules/bench/order-list/${item.id}`, label: `Bench Order List - ${item.title}` })),
        ...getOrderFormCaseOptions().map((item) => ({ to: `/entity-rules/bench/order-form/${item.id}`, label: `Bench Order Form - ${item.title}` })),
    ];

    return (
        <Space direction="vertical" style={{ width: '100%' }} size={16}>
            <Typography.Title level={2}>Ant Entity Rules Workspace</Typography.Title>
            <Card title="Fixtures">
                <List dataSource={fixtureLinks} renderItem={(item) => <List.Item><Link to={item.to}>{item.label}</Link></List.Item>} />
            </Card>
            <Card title="Benchmarks">
                <List dataSource={benchLinks} renderItem={(item) => <List.Item><Link to={item.to}>{item.label}</Link></List.Item>} />
            </Card>
        </Space>
    );
};

// mock/element-app/src/view/entity-rules/EntityRulesHome.vue
<template>
  <el-space direction="vertical" style="width: 100%">
    <h2>Element Entity Rules Workspace</h2>
    <el-card header="Fixtures">
      <el-space direction="vertical" alignment="start">
        <router-link to="/entity-rules/fixtures/user-list">Fixture User List</router-link>
        <router-link to="/entity-rules/fixtures/user-form">Fixture User Form</router-link>
      </el-space>
    </el-card>
    <el-card header="Benchmarks">
      <el-space direction="vertical" alignment="start">
        <router-link v-for="item in listCases" :key="item.id" :to="`/entity-rules/bench/user-list/${item.id}`">
          Bench User List - {{ item.title }}
        </router-link>
        <router-link v-for="item in formCases" :key="item.id" :to="`/entity-rules/bench/user-form/${item.id}`">
          Bench User Form - {{ item.title }}
        </router-link>
      </el-space>
    </el-card>
  </el-space>
</template>

<script setup lang="ts">
import { getUserFormCaseOptions, getUserListCaseOptions } from '../../service/entity-rules/case-service';

const listCases = getUserListCaseOptions();
const formCases = getUserFormCaseOptions();
</script>
